### ISSUE TITLE
Segment onIntegrationReady

### ISSUE THREAD

**Issue by adef145** [Appboy/appboy-segment-android-sample#1]
Why onIntegrationReady on Segment never called?
Is there missing configuration on my segment or  something?
I already put Segment key in AppboySegmentApplication. And put Appboy key & group key in Segment dashboard.

**Comment by chshapiro** [comment]
Hey @adef145,

Thank you for reporting this issue. It seems like you are having trouble integrating the Appboy Segment SDK on Android. If that's the case:
- Can you make sure you followed the integration correctly according to the docs here https://segment.com/docs/integrations/appboy/#integrating? 
- Can you check that you configured everything properly on the Segment dashboard?

Please let me know if you are still seeing the issue after the above steps, or if I misunderstood your issue.

Thanks, 
Chava

**Comment by adef145** [comment]
all fine now..
thank you for your respond..
